#!/bin/bash
mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<EOF
USE $MYSQL_DATABASE;

CREATE TABLE IF NOT EXISTS sensorData (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name ENUM('pH', 'conductivity', 'height'),
    reading FLOAT(7,3),
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE USER '$SENSOR_USER'@'%' IDENTIFIED BY '$SENSOR_PASSWORD';
GRANT INSERT ON $MYSQL_DATABASE.* TO '$SENSOR_USER'@'%';

CREATE USER '$SCREEN_USER'@'%' IDENTIFIED BY '$SCREEN_PASSWORD';
GRANT SELECT ON $MYSQL_DATABASE.* TO '$SCREEN_USER'@'%';

FLUSH PRIVILEGES;

EOF